services:
  git-server:
    build:
      context: .
      args:
      - GIT_USER_UID=${GIT_USER_UID:-1000}
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
      - ./public-keys:/home/git/public-keys:ro
      - ./repositories:/r
    restart: unless-stopped